# Generated by Django 5.0.10 on 2024-12-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_place', models.CharField(blank=True, max_length=100)),
                ('hotel_phone', models.CharField(blank=True, max_length=100)),
                ('hotel_adress', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('deluxe', 'Deluxe')], max_length=20)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('sub_admin', 'Sub_Admin'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_adress', models.CharField(blank=True, max_length=500)),
                ('customer_email', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_points', models.IntegerField(default=0)),
                ('customer_is_premium', models.BooleanField(default=False)),
                ('customer_status', models.CharField(choices=[('check_in', 'Check_in'), ('waiting', 'Waiting'), ('check_out', 'Check_out')], default='waiting', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
