# Generated by Django 5.0.10 on 2024-12-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_registration',
            old_name='hotel_adress',
            new_name='hotel_address',
        ),
    ]
