# Generated by Django 5.0.10 on 2024-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_hotel_adress_hotel_registration_hotel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_registration',
            name='hotel_id',
        ),
        migrations.AlterField(
            model_name='hotel_registration',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_registration',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_registration',
            name='hotel_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_registration',
            name='hotel_place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
